export const targets = [
    "dog",
    "cat",
    "elephant",
    "lion",
    "tiger",
    "giraffe",
    "zebra",
    "bear",
    "fish",
    "penguin",
    "panda",
    "koala",
    "dolphin",
    "whale",
    "octopus",
    "rabbit",
    "fox",
    "deer",
    "owl",
    "snake",
    "kangaroo",
];

export const colors = ["red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "gray", "black", "white", "cyan", "magenta", "teal"];
